# Site settings
title: Abhilash Blog
header-img: img/home-bg.jpg
email: i@abhilashgoyal.com
copyright_name: Meanwhile no copyright
description: "This is Abhlash Goyal personal Blog. I am passionately curious about SDN/NFV and other network technology. I belong to Uttrakhand. You can reach to me for any help 
                relating to Networking or travelling ..."
baseurl: ""
url: "http://abhilashgoyal.com"
twitter_username: abhilashgoyal4
github_username:  abhilashgoyal
facebook_username:  goyalabhilash
email_username: abhilashgoyal4@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-modernist